### ISSUE TITLE
请问转换后的onnx是否可以转换为openvino模型

### ISSUE THREAD

**Issue by Dandelion111** [RapidAI/PaddleOCRModelConverter#1]
请问转换后的onnx是否可以转换为openvino模型

**Comment by benjaminwan** [comment]
1. 不了解是否能够转换。
2. 推理的话，onnx支持直接调用openvino来进行推理：https://onnxruntime.ai/docs/execution-providers/OpenVINO-ExecutionProvider.html
3. 没有尝试过，所以无法给出什么说法，好不好用，能不能用，onnx openvino会不会比onnx cuda快，支持加速的层或算子多不多，都不清楚。

**Comment by Dandelion111** [comment]
> 1. 不了解是否能够转换。
> 2. 推理的话，onnx支持直接调用openvino来进行推理：https://onnxruntime.ai/docs/execution-providers/OpenVINO-ExecutionProvider.html
> 3. 没有尝试过，所以无法给出什么说法，好不好用，能不能用，onnx openvino会不会比onnx cuda快，支持加速的层或算子多不多，都不清楚。

好的，感谢回复
